[package]
name = "drv-stm32wb-spi"
version = "0.1.0"
edition = "2021"

[dependencies]
ringbuf = { path = "../../lib/ringbuf" }
zerocopy = { workspace = true }
num-traits = { workspace = true }
vcell = { workspace = true }
stm32wb = { workspace = true }

[features]
wb55 = ["stm32wb/stm32wb55"]
