name = "flipper-zero"
target = "thumbv7em-none-eabihf"
board = "flipper-zero"
chip = "../../chips/stm32wb"
stacksize = 896

[kernel]
name = "flipper-zero"
requires = {flash = 20000, ram = 3136}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 2048}
start = true
stacksize = 1536
notifications = ["fault", "timer"]

[tasks.sys]
name = "drv-stm32xx-sys"
features = ["wb55"]
priority = 1
max-sizes = {flash = 4096, ram = 1024}
uses = ["rcc", "gpios1", "gpios2", "gpios3"]
start = true
task-slots = ["jefe"]

[tasks.i2c_driver]
name = "drv-stm32xx-i2c-server"
features = ["wb55"]
priority = 2
max-sizes = {flash = 16384, ram = 4096}
uses = ["i2c1"]
start = true
task-slots = ["sys"]
notifications = ["i2c1-irq"]

[tasks.spi1_driver]
name = "drv-stm32wb-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 2048}
features = ["spi1", "wb55"]
uses = ["spi1"]
start = true
notifications = ["spi-irq"]
interrupts = {"spi1.irq" = "spi-irq"}
stacksize = 880
task-slots = ["sys"]

[tasks.spi1_driver.config.spi]
global_config = "spi1"

[tasks.spi2_driver]
name = "drv-stm32wb-spi-server"
priority = 2
max-sizes = {flash = 16384, ram = 2048}
features = ["spi2", "wb55"]
uses = ["spi2"]
start = true
notifications = ["spi-irq"]
interrupts = {"spi2.irq" = "spi-irq"}
stacksize = 880
task-slots = ["sys"]

[tasks.spi2_driver.config.spi]
global_config = "spi2"

[tasks.i2c_driver.interrupts]
"i2c1.event" = "i2c1-irq"
"i2c1.error" = "i2c1-irq"

[tasks.display]
name = "drv-flipper-display-server"
priority = 3
start = true
task-slots = ["sys", "spi2_driver"]
stacksize = 4096

[tasks.input]
name = "drv-flipper-input"
priority = 3
start = true
task-slots = ["sys", "i2c_driver"]
uses = ["syscfg", "exti"]
notifications = ["exti-exti3-irq", "exti-exti9_5-irq", "exti-exti15_10-irq", "timer"]

[tasks.input.interrupts]
"exti.exti3" = "exti-exti3-irq"
"exti.exti9_5" ="exti-exti9_5-irq"
"exti.exti15_10" = "exti-exti15_10-irq"

#[tasks.demo]
#name = "task-flipper-demo"
#priority = 4
#start = true
#task-slots = ["display"]
#stacksize = 2048

[tasks.spectrum_analyzer]
name = "task-flipper-spectrum-analyzer"
priority = 4
start = true
task-slots = ["display", "spi1_driver"]
stacksize = 3072

[tasks.blink]
name = "task-blink"
priority = 5
start = true
task-slots = ["sys", "i2c_driver"]

[tasks.idle]
name = "task-idle"
priority = 6
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[config]
[config.spi.spi1]
controller = 1
fifo_depth = 4

[config.spi.spi1.mux_options.subghz]
outputs = [
    {port = "A", pins = [5], af = 5},
    {port = "B", pins = [5], af = 5},
]
input = {port = "B", pin = 4, af = 5}

[config.spi.spi1.devices.subghz]
mux = "subghz"
cs = [{port = "D", pin = 0}]
clock_divider = "Div8"

[config.spi.spi2]
controller = 2
fifo_depth = 4

[config.spi.spi2.mux_options.display]
outputs = [
    {port = "B", pins = [15], af = 5},
    {port = "D", pins = [1], af = 5},
]
input = {port = "C", pin = 2, af = 5}

[config.spi.spi2.devices.display]
mux = "display"
cs = [{port = "C", pin = 11}]
clock_divider = "Div16"

[[config.i2c.controllers]]
controller = 1

[config.i2c.controllers.ports.A]
scl.pin = 9
sda.pin = 10
af = 4

[[config.i2c.devices]]
controller = 1
address = 0x30
device = "lp5562"
description = "LED controller"

[[config.i2c.devices]]
controller = 1
address = 0x6b
device = "bq25896"
description = "Battery controller"
