name = "flipper-zero"
target = "thumbv7em-none-eabihf"
board = "flipper-zero"
chip = "../../chips/stm32wb"
stacksize = 896

[kernel]
name = "flipper-zero"
requires = {flash = 20000, ram = 3072}
#
# For the kernel (and for any task that logs), we are required to enable
# either "itm" (denoting logging/panicking via ARM's Instrumentation Trace
# Macrocell) or "semihosting" (denoting logging/panicking via ARM
# semihosting).  We are biased to ITM because semihosting is excruciatingly
# slow (it is breakpoint based) and has an undesirable failure mode if logging
# output is generated and debugger is not attached (namely, the target stops).
# If one does choose to change this to semihosting for purposes of
# development, be sure to also change it in every task of interest.
#
features = ["itm"]

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 2048}
start = true
features = ["itm"]
stacksize = 1536

[tasks.sys]
name = "drv-stm32xx-sys"
features = ["wb55"]
priority = 1
max-sizes = {flash = 4096, ram = 1024}
uses = ["rcc", "gpios1", "gpios2", "gpios3"]
start = true

[tasks.blink]
name = "task-blink"
priority = 3
start = true
task-slots = ["sys"]

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true
